# Generated by Django 2.1 on 2018-04-18 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CapabilitiesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capability_name', models.CharField(max_length=200)),
                ('capability_inputs', models.CharField(max_length=200)),
                ('capability_type', models.CharField(choices=[('type1', 'type1'), ('type2', 'type2'), ('type3', 'type3'), ('type4', 'type4'), ('type5', 'type5')], default='type1', max_length=20)),
            ],
        ),
    ]
