# Generated by Django 2.1 on 2018-04-23 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capabilities_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='capabilitiesmodel',
            old_name='capability_inputs',
            new_name='plugin_capability_name',
        ),
        migrations.RemoveField(
            model_name='capabilitiesmodel',
            name='capability_type',
        ),
    ]
