sudo: required

language: python

python:
  - "3.6"

services:
  - docker

before_install:
  - git clone  https://github.com/ramrod-project/frontend-ui.git

install:
#  - pip install -r requirements.txt
  - pip install django==2.0.1 pytest pytest-django docker rethinkdb

# For when we have unit tests
before_script:
  - docker run -d -p 28015:28015 ramrodpcp/database-brain
  - pytest pcp_alpha

script:
#  - if [ "$TRAVIS_BRANCH" != "master"  ];
#    then docker build -t ramrodpcp/frontend-ui:$TRAVIS_BRANCH . ;
#    else docker build -t ramrodpcp/frontend-ui:latest . ;
#    fi
#
#  - if [ "$TRAVIS_BRANCH" != "master"  ];
#    then docker run -d --rm --name frontend -e "STAGE=DEV" -e "LOGLEVEL=DEBUG"
#    -v /var/run/docker.sock:/var/run/docker.sock ramrodpcp/frontend-ui:$TRAVIS_BRANCH;
#    else docker run -d --rm --name frontend -e "STAGE=PROD" -e "LOGLEVEL=DEBUG"
#    -v /var/run/docker.sock:/var/run/docker.sock ramrodpcp/frontend-ui:latest ;
#    fi

#  - if [ "$TRAVIS_BRANCH" != "master"  ];
#    then docker build -t ramrodpcp/frontend-ui:$TRAVIS_BRANCH . ;
#    else docker build -t ramrodpcp/frontend-ui:latest . ;
#    fi
#  - if [ "$TRAVIS_BRANCH" != "master"  ];
#    then docker run -d --rm --name frontend -p 8080:8080 ramrodpcp/frontend-ui:$TRAVIS_BRANCH ;
#    else docker run -d --rm --name frontend -p 8080:8080 ramrodpcp/frontend-ui:latest ;
#    fi

  - docker build -t ramrodpcp/frontend-ui .
  - docker run -d --rm --name frontend -p 8080:8080 ramrodpcp/frontend-ui
    fi

  # This will eventually be for more integration testing
  - sleep 5
#  - docker ps
  # Check to see if page is up
  - curl http://127.0.0.1:8080
  - docker stop frontend

after_success:
  - if [ "$TRAVIS_BRANCH" = "qa"  ] || [ "$TRAVIS_BRANCH" = "master"  ];
    echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin; fi
  - if [ "$TRAVIS_BRANCH" = "QA"  ];
    then docker push ramrodpcp/frontend-ui:$TRAVIS_BRANCH; fi
  - if [ "$TRAVIS_BRANCH" = "master"  ];
    then docker push ramrodpcp/frontend-ui:latest; fi

notifications:
  slack: ramrod-project:GDF82rRYDg3KSekrT3GA24qO